### ISSUE TITLE
[Bug] find the reason why some cmd has two 0x0x

### ISSUE THREAD

**Issue by nkysg** [starcoinorg/move#27]
# 🐛 Bug

## To reproduce
https://github.com/starcoinorg/move/pull/12/files/df541a10c64281c49e3a630fedd44fc4962a86c8#diff-c8cb8d8be76d63d9bacf0c4fd122c483dbfc3ed5722b3a1f919b0f8aa9366fdb

```shell
sandbox publish

# basics
sandbox generate struct-layouts --module storage/0x0x00000000000000000000000000000001/modules/M2.mv --struct C --type-args u64
```
**Code snippet to reproduce**
```rust
# Your code goes here
# Please make sure it does not require any external dependencies
```

**Stack trace/error message**
```
// Paste the output here
```

## System information

**Please complete the following information:**
- 
- 
-

**Comment by jiangying000** [comment]
这么好像还没搞定，https://github.com/starcoinorg/move/pull/12#discussion_r975054701_ 这个问题还在

**Comment by nkysg** [comment]
那再看下

**Comment by jiangying000** [comment]
这些测试在 https://github.com/move-language/move/commit/2ab0b168c28504a3a586e64f9ae10f97f4b40b69 重构过，感觉starcoin-main上面不太好调整。dev 分支也没有这些 0x0x 问题，感觉先等 https://github.com/move-language/move/pull/441 完成，然后 dev 分支后续调整，如果 dev 未来合并了，这个可以直接忽略了
