### ISSUE TITLE
[dev Bug] run_metatest  error

### ISSUE THREAD

**Issue by nkysg** [starcoinorg/move#29]
# 🐛 Bug

## To reproduce
https://github.com/starcoinorg/move/blob/dev/language/tools/move-cli/tests/cli_tests.rs#L20
```rust
#[test]
fn run_metatest() {
    let path_cli_binary = get_cli_binary_path();
    let path_metatest = get_metatest_path();

    // local workspace + with coverage
    assert!(test::run_all(&path_metatest, path_cli_binary.as_path(), false, true).is_ok());

    // temp workspace + with coverage
    assert!(test::run_all(&path_metatest, &path_cli_binary, true, true).is_ok());

    // local workspace + without coverage
    assert!(test::run_all(&path_metatest, &path_cli_binary, false, false).is_ok());

    // temp workspace + without coverage
    assert!(test::run_all(&path_metatest, &path_cli_binary, true, false).is_ok());
}
```
**Code snippet to reproduce**
```rust
# Your code goes here
# Please make sure it does not require any external dependencies
```

**Stack trace/error message**
```
// Paste the output here
```

## System information

**Please complete the following information:**
- 
- 
-

**Comment by jiangying000** [comment]
二分法测了下这个测试从 https://github.com/starcoinorg/move/commit/cd7fbe9abbf7424a03b91a394d10a0646e608edd 开始失败

复现方法：
`git reset  --hard cd7fbe9ab && cargo test --package move-cli --test cli_tests -- run_metatest --exact --nocapture`

错误是：

> Trace file "/home/jiangying/code/starcoinorg/move/language/tools/move-cli/tests/metatests/cov/plain/trace" not found: coverage is only available with at least one `run` command in the args.txt (after a `clean`, if there is one)
> Test cov/plain/args.txt failed with error: Expected output differs from actual output:
> Command `sandbox publish`:
> Command `sandbox run scripts/test.move --dry-run`:
> Execution failed due to unresolved type argument(s) (i.e., `--type-args 0x1::M:T` when there is no module named M at 0x1 or no type named T in module 0x1::M)
> 

---

和 dev 最新代码 4018ec174ef53ad0ee0e6258945bcc69a0faaf84 的错误还不一样，dev 的报错：

> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: VMError { major_status: DUPLICATE_NATIVE_FUNCTION, sub_status: None, message: None, exec_state: None, location: Undefined, indices: [], offsets: [] }', language/tools/move-cli/src/sandbox/commands/run.rs:77:35

**Comment by nkysg** [comment]
DUPLICATE_NATIVE_FUNCTION 这个报错是因为我在cherry-pick时候all_natives和nursery_natives里面native functions有重复，这个已经修改了。相关代码如下
```rust
fn main() -> Result<()> {
    let error_descriptions: ErrorMapping = bcs::from_bytes(move_stdlib::error_descriptions())?;
    let cost_table = &move_vm_test_utils::gas_schedule::INITIAL_COST_SCHEDULE;
    let addr = AccountAddress::from_hex_literal("0x1").unwrap();
    let natives = all_natives(addr, GasParameters::zeros())
        .into_iter()
        .chain(nursery_natives(addr, NurseryGasParameters::zeros()))
        .collect();

    move_cli::move_cli(natives, cost_table, &error_descriptions)
}
```

**Comment by jiangying000** [comment]
这个是否可以弄个小的pr修下

**Comment by nkysg** [comment]
可以修下DUPLICATE_NATIVE_FUNCTION这个，但是dev分支会基于最新的move来patch,https://github.com/starcoinorg/move/pull/36

**Comment by nkysg** [comment]
dev分支改名成了dev_origin,因为 https://github.com/starcoinorg/move/pull/36, 这里是https://github.com/starcoinorg/move/commit/58e4a01503bc7b8608a2615b81439d873c3c2d5b run_metatest修改

**Comment by jiangying000** [comment]
> dev分支改名成了dev_origin,因为 #36, 这里是[58e4a01](https://github.com/starcoinorg/move/commit/58e4a01503bc7b8608a2615b81439d873c3c2d5b) run_metatest修改

收到
